// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBViXLiKkM52_sVzBYaDanQItTq-U2VigE',
    appId: '1:623733229484:web:6deccac42d032084709c09',
    messagingSenderId: '623733229484',
    projectId: 'notificationtest-acf41',
    authDomain: 'notificationtest-acf41.firebaseapp.com',
    storageBucket: 'notificationtest-acf41.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjRrM-NuB6nfbqb_PhACqVQdWj7EP_t9c',
    appId: '1:623733229484:android:36c4451e71c3c6ab709c09',
    messagingSenderId: '623733229484',
    projectId: 'notificationtest-acf41',
    storageBucket: 'notificationtest-acf41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2zu-_vOmdwerDKITCO0RbJqv7_ONnch0',
    appId: '1:623733229484:ios:6ad0965933d7af77709c09',
    messagingSenderId: '623733229484',
    projectId: 'notificationtest-acf41',
    storageBucket: 'notificationtest-acf41.firebasestorage.app',
    iosBundleId: 'com.example.apknotif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2zu-_vOmdwerDKITCO0RbJqv7_ONnch0',
    appId: '1:623733229484:ios:6ad0965933d7af77709c09',
    messagingSenderId: '623733229484',
    projectId: 'notificationtest-acf41',
    storageBucket: 'notificationtest-acf41.firebasestorage.app',
    iosBundleId: 'com.example.apknotif',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBViXLiKkM52_sVzBYaDanQItTq-U2VigE',
    appId: '1:623733229484:web:6e9c2a06fec78e94709c09',
    messagingSenderId: '623733229484',
    projectId: 'notificationtest-acf41',
    authDomain: 'notificationtest-acf41.firebaseapp.com',
    storageBucket: 'notificationtest-acf41.firebasestorage.app',
  );
}
