// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'A',
    appId: 'A',
    messagingSenderId: 'A',
    projectId: 'A',
    authDomain: 'A',
    storageBucket: 'A',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'B',
    appId: 'B',
    messagingSenderId: 'B',
    projectId: 'B',
    storageBucket: 'B',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'C',
    appId: 'C',
    messagingSenderId: 'C',
    projectId: 'C',
    storageBucket: 'C',
    iosBundleId: 'C',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'D',
    appId: 'D',
    messagingSenderId: 'D',
    projectId: 'D',
    storageBucket: 'D',
    iosBundleId: 'D',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'E',
    appId: 'E',
    messagingSenderId: 'E4',
    projectId: 'E',
    authDomain: 'E',
    storageBucket: 'E',
  );
}
